apiVersion: batch/v1
kind: Job
metadata:
  name: playlist-ml-job-8  # Change 
  namespace: othmane
spec:
  template:
    spec:
      containers:
      - name: playlist-ml
        image: quay.io/othmaneechchabi/playlist-ml:0.6
        command: ["python", "ml_rules.py"]
        env:
          - name: DATASET_PATH
            value: "/home/datasets/spotify/2023_spotify_ds2.csv"  # Change
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        volumeMounts:
          - name: shared-volume
            mountPath: /app/model
          - name: dataset-volume
            mountPath: /home/datasets/spotify
      imagePullSecrets:
        - name: quay-secret
      restartPolicy: Never
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: project2-pvc-othmane
        - name: dataset-volume
          hostPath:
            path: /home/datasets/spotify
            type: Directory
  backoffLimit: 1
