apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-othmane
  namespace: othmane
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: othmane
