apiVersion: v1
kind: Service
metadata:
  name: playlist-api-service
  namespace: othmane
spec:
  type: NodePort
  ports:
    - port: 52001
      targetPort: 52001
      nodePort: 32001  # Choose a valid port in the allowed range
  selector:
    app: playlist-api
