apiVersion: v1
kind: Service
metadata:
  name: playlist-api-service
  namespace: othmane
spec:
  type: NodePort
  selector:
    app: playlist-api
  ports:
    - port: 52001
      targetPort: 5000
      nodePort: 32003

